runmode: debug # 开发模式, debug, release, test
addr: :8080
name: todolist
url: http://127.0.0.1:8080
max_ping_count: 10
jwt_secret: Rtg8BPKtodOlIstWNLiBackEnDRgq0iBb5FIFV
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_apiserver
  addr: 0.0.0.0:3306
  username: root
  password: root
